services:

  # mysql service
  mysql:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - ./.env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - wpsite

  # Wordpress service
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - ./.env
    environment:
      WP_DB_HOST: mysql
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASSWORD: ${WP_DB_PASSWORD}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWD: ${WP_ADMIN_PASSWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - ../wordpress:/var/www/html
    networks:
      - wpsite

  # NGINX service
  nginx:
    depends_on: 
      - wordpress
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - ./.env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - 443:443
    volumes:
      - ../wordpress:/var/www/html
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db:
