version: '3.1'

services:

  # mysql service
  mysql:
    build: ./services/mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: wp_db
      MARIADB_HOST: "%"
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - db:/var/lib/mysql
    networks:
      - wpsite

  wordpress:
    depends_on:
      - mysql
    build: ./services/wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_db
      WP_URL: 10.12.179.248:8080
      WP_TITLE: Anouar
      WP_ADMIN: anouar
      WP_ADMIN_PASSWD: 1234
      WP_ADMIN_EMAIL: test@test.com
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wpsite

  # NGINX service
  nginx:
    depends_on: 
      - wordpress
    build: ./services/nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:443
    volumes:
      - ./wordpress:/var/www/html
    networks:
      wpsite:
        aliases:
          - wordpress

networks:
  wpsite:
    driver: bridge

volumes:
  db:
