#!/bin/sh

echo "MARIADB_DATABASE: $MARIADB_DATABASE"
echo "MARIADB_USER: $MARIADB_USER"
echo "MARIADB_PASSWORD: $MARIADB_PASSWORD"

cat << EOF > wp.db
  FLUSH PRIVILEGES;
  CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;
  CREATE USER IF NOT EXISTS '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';
  GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'%';
  FLUSH PRIVILEGES;
EOF
mariadbd --user=mysql --bootstrap < wp.db

exec "$@"
